modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/teamauroramods/Abundance/issues"

[[mods]]
    modId="abundance"
    version="${file.jarVersion}"
    displayName="Abundance"
    displayURL="https://discord.gg/VzXSCFp"
    logoFile="logo.png"
    authors="Team Aurora"
    description="New flowers and flowery biomes!"

[[dependencies.abundance]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.abundance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.abundance]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="AFTER"
    side="BOTH"